---
title: "practice"
output: html_document
date: "2026-05-18"
# おためし作業用
---

# source
```{r}
source("preparation.R")
```




```{r}
table(df$v9_farming_intention_w2,
      df$v15_successor_w2) 
```

```{r}
table(df$v19_farming_intention_w3,
      df$v17_successor_w3)
```

```{r}
prop.table(
  table(df$v15_successor_w2,
        df$v9_farming_intention_w2),
  margin = 1
)
```
```{r}
table(df$v17_successor_w3,
      df$v20_farming_type_w3) 
```

```{r}
table(
  df$v32_successor_w4, 
  df$v36_farming_type_w4
)
```

```{r}
df <- df |> 
  mutate(
    v10_farming_type_w2 =
      case_when(
        v10_farming_type_w2_individual_farm == 1 ~ "個人経営",
        v10_farming_type_w2_group_farming == 1 ~ "集落営農",
        v10_farming_type_w2_corporate_farming == 1 ~ "法人",
        v10_farming_type_w2_dont_know == 1 ~ "わからない",
        v10_farming_type_w2_other == 1  ~ "その他",
        TRUE ~ NA_character_
      )
  ) |> 
  mutate(
    v10_farming_type_w2 =
      factor(v10_farming_type_w2,
             levels = c("個人経営", "集落営農", "法人", "わからない", "その他"))
  )



```




```{r}
df <- df |> 
  mutate(
    v20_farming_continuation_management_type = recode(
      v20_farming_continuation_management_type,
      `1` = "家族経営",
      `2` = "農業生産法人",
      `3` = "集落営農組織",
      `4` = "その他",
      .default = NA_character_
    )
    )
```


```{r}
df$v32_successor_yes_w4 == 1


df <- df |> 
  mutate(
    v32_successor_w4 =
      case_when(
        df$v32_successor_yes_w4 == 1 ~ "いる",
        df$v32_successor_no_w4 == 1 ~ "いない",
        df$v32_successor_dontknow_w4 == 1 ~ "わからない",
        TRUE ~ NA_character_
      )
  ) |> 
  mutate(
    v32_successor_w4 =
      factor(v32_successor_w4,
             levels = c("いる", "いない", "わからない"))
  )

df$v32_successor_w4 |> table()
```


```{r}
table(
  df$v7_machinery_damage_status,
  df$v15_successor_w2
)
```


```{r}
table(
  df$district_w3, 
  df$v19_farming_intention_w3
) |> 
  as.data.frame.matrix()
```


```{r}
table(
  df$district_w3,
  df$v20_farming_type_w3
) |> 
  as.data.frame.matrix()
```


```{r}
table(
  df$v30_machine_loss_number_w3,
  df$v20_farming_type_w3
) |> 
  as.data.frame.matrix()
```

```{r}
table(
  df$v31_machine_available_number_w3,
  df$v20_farming_type_w3
) |> 
  as.data.frame.matrix()
```

```{r}
df |>
  group_by(district_w3) |>
  summarise(
    loss_mean =
      mean(v30_machine_loss_number_w3, na.rm = TRUE),
    n_loss =
      sum(!is.na(v30_machine_loss_number_w3)),
    available_mean =
      mean(v31_machine_available_number_w3, na.rm = TRUE),
    n_available =
      sum(!is.na(v31_machine_available_number_w3))
  )
```




```{r}

table(df$district_w2, df$member)
table(df$v9_farming_intention_w2, df$member)

```

# データ結合練習

## データ読み込み
```{r}
df_id_name <- read_excel("data/data_id_name.xlsx")
dw1 <- read_excel("data/data_shichigawahama_w1.xlsx")
dw2 <- read_excel("data/data_shichigawahama_w2.xlsx")
dw3 <- read_excel("data/data_shichigawahama_w3.xlsx")
dw4 <- read_excel("data/data_shichigawahama_w4.xlsx")

```

## 重複IDがないかチェック
```{r}
df_id_name |> count(id) |> filter(n > 1)
dw1 |> count(id) |> filter(n > 1)
dw2 |> count(id) |> filter(n > 1)
dw3 |> count(id) |> filter(n > 1)
dw4 |> count(id) |> filter(n > 1)
```
## idをキーにしてデータ結合
```{r}
df <- list(df_id_name, dw1, dw2, dw3, dw4) |> 
  reduce(full_join, by = "id")

df

```

